[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "inptk"
version = "0.4.2"
description = "INP-toolkit: workflows for ice nucleating particle freezing assays"
authors = [
    {name = "INP-toolkit contributors"}
]
license = {text = "AGPL-3.0"}
readme = "README.md"
keywords = ["freezing", "ice nucleation", "INP", "Icescopy", "OLAF"]


requires-python = ">=3.11.0"
dependencies = [
    "numpy>=2.0.0",
    "pandas>=2.2.3",
    "scipy>=1.13",
]

[project.scripts]
inptk = "inptk.cli:main"

[project.urls]
"Repository" = "https://github.com/bochens/inptk"
"Wiki" = "https://github.com/bochens/inptk/wiki"

[project.optional-dependencies]
plot = [
    "matplotlib>=3.10.3",
]
dev = [
    "ruff>=0.5.6",
    "pytest>=8.3.2",
    "mypy>=1.11.0",
    "bandit>=1.7.9",
    "pandas-stubs>=2.2.2.240603",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["I", "F", "E", "W"]

[tool.pytest.ini_options]
testpaths = "tests"
pythonpath = "src"

[tool.bandit]
exclude = ["tests"]
